spring:
  datasource:
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

jwt:
  signer: kms
  expiration: 600
  kid: "alias/jwt-signing-key-external"

server:
  port: 8080